# Generated by Django 4.2.13 on 2024-08-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeedocument_comment'),
        ('clients', '0003_contract_created_at_contract_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee'),
        ),
    ]
