# Generated by Django 4.2.13 on 2024-08-31 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0003_usergroups'),
        ('clients', '0005_client_created_at_client_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dicts.currency'),
        ),
    ]
