# Generated by Django 4.2.13 on 2024-09-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeedocument_comment'),
        ('dicts', '0004_alter_usergroups_group'),
        ('clients', '0007_alter_contract_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='value',
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='employees.employee')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.currency')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
