# Generated by Django 4.2.13 on 2024-09-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0005_rename_usergroups_usergroup_dimmention'),
        ('clients', '0008_remove_contract_currency_remove_contract_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='dimmention',
            field=models.ManyToManyField(blank=True, to='dicts.dimmention'),
        ),
    ]
