# Generated by Django 4.2.13 on 2024-09-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_rename_dimmention_contractitem_dimention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractitem',
            old_name='dimention',
            new_name='dimension',
        ),
    ]
