# Generated by Django 4.2.13 on 2024-09-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0007_rename_dimention_dimension_alter_dimension_options'),
        ('employees', '0007_employeedocument_comment'),
        ('clients', '0011_rename_dimention_contractitem_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(upload_to='SalesInvoice/')),
                ('contract_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.contractitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='employees.employee')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.currency')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
