# Generated by Django 4.2.13 on 2024-07-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_archived_employees', 'Can view archived employee list'), ('view_all_employee_details', 'Can view all employee details')]},
        ),
    ]
