# Generated by Django 4.2.13 on 2024-07-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_employee_list', 'Can view employee list'), ('can_view_archived_employees', 'Can view archived employee list'), ('view_all_employee_details', 'Can view all employee details'), ('can_set_user_roles', 'Can set user roles')]},
        ),
    ]
