# Generated by Django 4.2.13 on 2024-08-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly (B2B)'), ('monthly', 'Monthly (EMployment Contract)')], max_length=20)),
                ('chargable_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('PLN', 'Polish Zloty')], max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
