# Generated by Django 4.2.13 on 2024-08-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerate',
            name='reference_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedocument'),
        ),
        migrations.AlterField(
            model_name='employeerate',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'Hourly (B2B)'), ('monthly', 'Monthly (Employment Contract)')], max_length=20),
        ),
    ]
