# Generated by Django 4.2.13 on 2024-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeerate_reference_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
