# Generated by Django 4.2.13 on 2024-09-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0008_employeedocumenttypes'),
        ('employees', '0007_employeedocument_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.currency'),
        ),
    ]
