# Generated by Django 4.2.13 on 2024-09-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0009_alter_employeedocumenttypes_options_and_more'),
        ('employees', '0011_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.employeedocumenttypes'),
        ),
    ]
