# Generated by Django 4.2.13 on 2024-09-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employeedocument_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedocument',
            old_name='document_file',
            new_name='file',
        ),
    ]
