# Generated by Django 4.2.13 on 2024-08-31 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dicts', '0002_alter_currency_options_currency_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'User Groups',
                'ordering': ['name'],
            },
        ),
    ]
