# Generated by Django 4.2.13 on 2024-09-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_contractitem_dimmention'),
        ('dicts', '0005_rename_usergroups_usergroup_dimmention'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dimmention',
            new_name='Dimention',
        ),
        migrations.AlterModelOptions(
            name='dimention',
            options={'ordering': ['name'], 'verbose_name_plural': 'Dimentions'},
        ),
    ]
