# Generated by Django 4.2.13 on 2024-09-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_rename_dimention_contractitem_dimension'),
        ('dicts', '0006_rename_dimmention_dimention_alter_dimention_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dimention',
            new_name='Dimension',
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ['name'], 'verbose_name_plural': 'Dimensions'},
        ),
    ]
