# Generated by Django 4.2.13 on 2024-11-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='valid_to',
        ),
    ]
